Fueled pack
erasels/Packmaster-Expansion-Packs pull request #2
Opened 2023-07-05 16:03 UTC by bkerns724

Some people just want to watch the Spire burn.

2023-07-06 03:13 UTC, modargo requested changes
Looks pretty good. We already discussed design and balance for most of the cards and the redesigned cards look reasonable, though I'm still a bit concerned about Burn Bright. 

Other than that, the only significant issue I saw was with `PlayWithFireAction`. There's also a few smaller issues I left comments about.

Once those issues are resolved this should be ready to merge!

2023-07-06 14:32 UTC, bkerns724 commented on src/main/java/thePackmaster/actions/fueledpack/PlayingWithFireAction.java
> +        att(new RollAction(sides, 0, dieConsumer, false));
I got a pull request for that accepted for the features/expansionpacks branch, but it isn't on the main branch.  Should I submit a pull request for that branch or is expansion packs branch getting merged in?

2023-07-06 14:36 UTC, bkerns724 commented on src/main/resources/anniv5Resources/localization/eng/fueledpack/Cardstrings.json
> +    "UPGRADE_DESCRIPTION": "Exhaust all *Hot *Ash in your hand. NL Add a random Upgraded card into your hand for each Exhausted card."
I failed to update the card properly, the description is what its supposed to do.

2023-07-06 14:40 UTC, bkerns724 commented on src/main/java/thePackmaster/cards/fueledpack/BurningStrike.java
> +public class BurningStrike extends AbstractFueledCard {
Several playtests.  The old version just didn't feel like it had enough oomph, I often regretted taking it in act 1 where you want to be picking up your damage commons.

2023-07-06 14:44 UTC, erasels commented on src/main/java/thePackmaster/actions/fueledpack/PlayingWithFireAction.java
> +        att(new RollAction(sides, 0, dieConsumer, false));
That can't be. The feature branch is merged into main. You should recompile the packmaster jar locally so you're working with the newest version

2023-07-06 14:50 UTC, bkerns724 commented on src/main/java/thePackmaster/cards/fueledpack/FireOfLife.java
> +public class FireOfLife extends AbstractFueledCard {
I'm glad you like it

2023-07-06 14:56 UTC, bkerns724 commented
I believe this is now ready once I know what to do with the dice PR for Packmaster repo.

2023-07-06 16:38 UTC, modargo commented on src/main/java/thePackmaster/actions/fueledpack/PlayingWithFireAction.java
> +        att(new RollAction(sides, 0, dieConsumer, false));
I see the PR mentioned (https://github.com/erasels/PackmasterCharacter/pull/648/files) and it was merged. It looks to me like the issue is that it was merged _after_ the PR for the expansion packs branch was merged. So the changes are sort of marooned on a branch that's no longer being actively developed against.

Luckily this is easy to fix now that I see what happened. I've fixed this by merging the expansion packs feature branch again, see https://github.com/erasels/PackmasterCharacter/pull/649. Now if you pull in the most recent code from the Packmaster repo on the `main` branch and build that, it should work properly with this PR.

I've tested this myself locally and things seem to build and run properly now.

2023-07-06 16:43 UTC, modargo commented on src/main/java/thePackmaster/cards/fueledpack/BurningStrike.java
> +    }
With the name, this should have the strike tag: `tags.add(CardTags.STRIKE);`

2023-07-06 16:46 UTC, modargo commented on src/main/resources/anniv5Resources/images/cards/Conflaguration.png
There's no Burninate image and no Infernal Blaze image in the file list for the PR, so I'm pretty sure those are still missing and need to be added.

I ran things locally to confirm this. You can see that those two cards are getting card roller art.
![image](https://github.com/erasels/Packmaster-Expansion-Packs/assets/62083413/20cf1c8c-3344-443c-a55b-2f4263c1ee97)

Maybe you have the correct images locally but didn't add them to Git?

2023-07-11 16:59 UTC, bkerns724 commented on src/main/resources/anniv5Resources/images/cards/Conflaguration.png
Fixed.  Unless some sort of cache or something is tricking me again.

2023-07-11 17:00 UTC, bkerns724 commented
I think this is ready.  Sorry if I missed something.

2023-07-12 01:11 UTC, modargo commented
> I think this is ready. Sorry if I missed something.

Looks like Burning Strike is still missing the strike tag, but I'll just merge this and ad that in myself. I'm looking forward to playing with the release version of this pack!

2023-07-12 01:12 UTC, merged