Preliminary Disco Pack consideration
erasels/Packmaster-Expansion-Packs pull request #25
Opened 2023-11-10 01:08 UTC by NoMasPollo

![Disco Pack Display](https://github.com/erasels/Packmaster-Expansion-Packs/assets/65381377/4b84a16f-e6d9-45b3-977f-1a446a5e600d)
This is something i've been working on for a while. Obviously, its not done, the powers, cards, and pack dont have art yet but I do have someone I can ask to help me with that. This is more of asking if its balanced or too busted. I did add a secondBlock since initially I was using shenanigans with magic number but they would sometimes update strangely. If you know a better way of doing it please let me know bc i only use it once.

2023-11-10 08:20 UTC, erasels requested changes
Still formulating my thoughts on pack design and balance, here's just some small thigns I noticed in the code

2023-11-10 08:20 UTC, erasels commented on src/main/java/thePackmaster/actions/discopack/SpecificToHandFromDiscardAction.java
> +public class SpecificToHandFromDiscardAction extends AbstractGameAction {
`BetterDiscardPileToHandAction`
Exists, this is not needed

2023-11-10 08:20 UTC, erasels commented on src/main/java/thePackmaster/actions/discopack/AnyNumberDiscardAction.java
> +    }
This seems unneeded, just give the SelectCardsInHand action a a lamda with a for each loop that adds discardspecificcardaction on them.

That also will contain any patches made to the discard action.

2023-11-10 08:20 UTC, erasels commented on src/main/java/thePackmaster/vfx/discopack/SpotlightFXtest.java
> +public class SpotlightFXtest extends AbstractGameEffect {
Might be nice to rename this, test seems kind of weird here since it is being used

2023-11-10 08:20 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/discopack/Cardstrings.json
> +    "DESCRIPTION": "Place a card from your discard pile on top of your deck. NL ${ModID}:Smooth: Gain [E] .",
```suggestion
    "DESCRIPTION": "Place a card from your discard pile on top of your drawpile. NL ${ModID}:Smooth: Gain [E] .",
```

2023-11-10 08:20 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/discopack/Cardstrings.json
> +    "UPGRADE_DESCRIPTION": "Draw a card, then place a card from your discard pile on top of your deck. NL ${ModID}:Smooth: Gain [E] ."
```suggestion
    "UPGRADE_DESCRIPTION": "Draw a card, then place a card from your discard pile on top of your drawpile. NL ${ModID}:Smooth: Gain [E] ."
```

2023-11-10 08:20 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/discopack/Cardstrings.json
> +    "DESCRIPTION": "Deal !D! damage. NL Until next turn, whenever you discard a card gain !M! Block."
```suggestion
    "DESCRIPTION": "Deal !D! damage. NL Until the end of your turn, whenever you discard a card gain !M! Block."
```

2023-11-10 21:21 UTC, NoMasPollo commented
Honestly, I agree with most of the points here. Halfway through making the pack, I realized how actually hard it is to make a non-insular discard pack. A number of the cards went through a lot of changes to make them feel less bad (and funky chicken used to be an acro clone until i realized that it was literally just acro.) Some of the extremely recent changes were hard nerfs to a lot of the cards. I agree that some of them are a little bland, I think I was worried about complexity for the sake of complexity in how they worked. A big question is any restrictions on using other pack's gimmicks, I was thinking about using inspiration seeing as bard and this are both flavored towards music, or maybe making fast movements a flurry card as one of those powers where it really matters when you play it. Point move is intentionally rare infinite bait, though it originally just put the card into your hand. Is a rare 0e hologram without the block but with other upside op? Idk. One of the big problems was deciding what the commons did, especially the really basic ones. I might keep just one tbh, probably the block one. I'm gonna make a mockup of what this theoretic rework would be, now that I think of some alternatives.

1: Yeah, that's never actually used. I don't remember why I even put it in anymore.
2: Whoops, sorry I forgot to rename it from test since I haven't been working with it for a bit. Will fix.

2023-11-10 22:35 UTC, NoMasPollo commented
![disco display 2](https://github.com/erasels/Packmaster-Expansion-Packs/assets/65381377/81d642ba-8dc6-46df-8084-b19d76adb981)
Here's a potential rework I was looking at. Numbers subject to change. A lot of these have either used some mechanics from other packs or the original (more complex xd) concepts.

2023-11-11 14:17 UTC, erasels commented
Oh, I like the idea of including some Bard flavor via inspire.

Some notes:
Funky Chicken being 0 cost draw might still be an issue, infinites do not care about next turn.
Electric Slide: I don#t think your pack really needs to dabble in orbs, doesn't really fit. You've got eneough going on when just focusing on the basics around card manipulation.
Point Move, please go away from 0 cost draw card.
Fast movements will definitely have to be double checked value wise, it's basically the Bard's Form card if you have no cards in hand.
Explosive Finish: I don't think locking fits here and it adds a bit more complexity than the card should have in my opinion.


I don't think the pack is quite there yet, it doesn't really cleany integrate with other packs at the moment and the discard is still too heavily relied on. I liked the change to Fast movements, a nice way to implicity encourage discard but also allowing other archetypes to shine.
I'd say try to go for 3 cards that don't explicity mention discard at all.

Now that you've added inspiration your deck has a bit more identity in the role it tries to slot into. Since inspiration is easy to lose (by playing any attack ro block card) timing matters a lot, so maybe try adding a card that helps with it.
My thinking here is that inspiration likes big cards (so stuff like YMCA benfits the least from it counterintuitively) so it necessitates bigger cards being in hand when needed. Now how to mix that into discard...

2023-11-12 05:09 UTC, NoMasPollo commented
![image](https://github.com/erasels/Packmaster-Expansion-Packs/assets/65381377/22353774-8eb9-434c-8e43-fe06bac57618)
New concepts. One of the ones I am hesitant to change is YMCA and being tied to times, mostly because I already coded the vfx for it and it would cause me great pain to change that xd. This version takes advantage of how the amount2 of inspiration works. Note that there are a few rarity and type changes.

2023-11-12 10:43 UTC, erasels commented
Much better! This is starting to look great, some value tweaks and one more card rework and we should have it.

The Bump's block needs to be decreased a bit since it's basically free Block and upgrading both values by 4 is a bit much. I can see a 2 for each, or 4 for one. Or maybe a 3/1 split.

Point Move needs to go back the drawing board, it's fine if you want it to keep being a damage card, but right now it's a bit bland and also *very* slow. Compare it to rampage's values and even that is considered a bad card because it's too slow. It's a 11 damage card at base which isn't bad, but there's no real way to scale it and being discard fodder does not make for an interesting card.

Fast movements, as mentioned before, might have to be reduced to 25/50 inspiration or 3/2 cost with 50 constant inspiration. Or maybe changing the threshold to 2, a lot of avenues to tweak it so i'm not worried.

Explosive Finish looks interesting, playtesting will have to reveal if it's too easy to trigger for its large numbers or not. Wording wise, i'd probably remove the ", then". It might need a tune down on the numbers, we'll have to see.

YMCA's idea is fine, but right now it's a bit complex and hard to parse. I'd say limit it to gaining inspiration more times and increase the base gain by 5. We'll have to see if that feels like it scales too slowly or not, but I think it will be more healthy or the card as a whole even if the current idea is very flavorful.

2023-11-12 22:20 UTC, NoMasPollo commented
![image](https://github.com/erasels/Packmaster-Expansion-Packs/assets/65381377/38fde5e1-8269-4184-a0f6-ad048cf5de6e)

It's really hard coming up with that last card tbh. This should hopefully help make it feel better for scaling, as it gives "free" discard fodder as well as having a big damage hit. The idea with Fast Movements now that its rare, is that its a conditional sidegraded Splendid Form. If your hand is empty, it gives a 25 - 50 larger total % boost to cards, but the strength of splendid form is that it gives you all that value on one card which makes high values stronger. YMCA is now just farming 25% inspiration as much as possible to get a lot of value.

2023-11-14 10:10 UTC, erasels commented
What do you think about making Ste Tap ethereal, so you have to discard it (implicit synergy, yay) or play it to continue to be able tot let it generate a decent 2 cost?

2023-11-15 20:43 UTC, NoMasPollo commented
1: Sounds interesting, will definitely make it scale less though
2: Im not particularly attached to the name, but the idea was that it "dances" from your hand to your discard and back. Something along those lines would be fine.

2023-11-22 01:05 UTC, closed without merging

2024-01-05 17:19 UTC, erasels commented
@NoMasPollo no pressure since I'll start merging stuff in Febuary again, just curious if this pack is still in the works? I thought it was pretty cool and just want to make sure it's still on the radar :)

2024-01-05 22:56 UTC, NoMasPollo commented
Yeah, sorry I've had school but I'm working on getting art

On Fri, Jan 5, 2024, 09:20 erasels ***@***.***> wrote:

> @NoMasPollo <https://github.com/NoMasPollo> no pressure since I'll start
> merging stuff in Febuary again, just curious if this pack is still in the
> works? I thought it was pretty cool and just want to make sure it's still
> on the radar :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/erasels/Packmaster-Expansion-Packs/pull/25#issuecomment-1879012770>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APS2IAIVVCOP2X7ZL4XKX33YNAY4PAVCNFSM6AAAAAA7FN7TNOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZZGAYTENZXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>