needlework pack Without Images Or Thorough Testing
erasels/Packmaster-Expansion-Packs pull request #48
Opened 2024-03-09 12:51 UTC by Alchyr

just sticking this here to Add Stuff Later

2024-03-10 11:55 UTC, Alchyr commented
still needs power icons and some of the art is Iffy-ish,
power icons I can do myself

2024-03-14 16:30 UTC, erasels requested changes
Few string fixes, a hat and the missing power art and this pack should be good to go

2024-03-14 16:30 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/needleworkpack/Powerstrings.json
> +      "Whenever you play a card this turn, apply #b%1$d Weak to %2$s."
```suggestion
      "Whenever you play a card this turn, apply #b%1$d #yWeak to %2$s."
```

2024-03-14 16:33 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/needleworkpack/Powerstrings.json
> +      "This enemy's next Attack deals #b%d less damage."
Might make sense to say this creature's instead of enemy's since there are friendly monsters, not that I think it's likely to end up being on them

2024-03-30 15:24 UTC, Alchyr commented
note - haven't finished because I am not happy with current effect of Copy and Paste, it's not like.. *terrible*, but I am Not happy with it

2024-06-22 09:03 UTC, Alchyr commented
ok I think I'm satisfied with it

another contribution to lowering packmaster's winrate

well maybe, there's some strong cards in this one

2024-06-22 09:59 UTC, merged