Showman Pack
erasels/Packmaster-Expansion-Packs pull request #55
Opened 2024-05-01 15:03 UTC by Dayvig

2024-05-01 18:42 UTC, erasels requested changes
Ignoring the points from the other PR just makes me bring them back up

2024-05-01 18:42 UTC, erasels commented on src/main/java/thePackmaster/powers/showmanpack/HallOfMirrorsPower.java
> +    public HallOfMirrorsPower(AbstractCreature owner, int amount) {
Please use the packmaster abstract, it already implements two amount power

2024-05-01 18:42 UTC, erasels commented on src/main/java/thePackmaster/powers/showmanpack/MagicCylinderPower.java
> +            addToBot(new ReducePowerAction(owner, owner, this, 1));
Might be worth to directly reduce the power so you don't trigger the power more than you have chanrges with multi hits

2024-05-01 18:42 UTC, erasels commented on src/main/java/thePackmaster/powers/showmanpack/NowYouDontPower.java
> +        this.addToBot(new MakeTempCardInHandAction(toGenerate.makeCopy()));
```suggestion
        this.addToBot(new MakeTempCardInHandAction(toGenerate));
```
That action already makes a copy

2024-05-01 18:42 UTC, erasels commented on src/main/resources/anniv5Resources/localization/eng/showmanpack/Cardstrings.json
> +  "DESCRIPTION": "Gain !B! Block. NL Next turn, gain [E] .",
Look into dynamic descriptions for this, would be nice.

2024-05-14 18:24 UTC, erasels commented
@Dayvig any progress on this or did you lose interest?

2024-05-14 19:36 UTC, Dayvig commented
Just haven't gotten to it yet. I have some time today so I'll take another
look at the lingering issues-

On Tue, May 14, 2024, 2:24 PM erasels ***@***.***> wrote:

> @Dayvig <https://github.com/Dayvig> any progress on this or did you lose
> interest?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/erasels/Packmaster-Expansion-Packs/pull/55#issuecomment-2110851898>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWF7OWUKKNJS4VO7IE7KULZCJJGTAVCNFSM6AAAAABHCDBKE6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJQHA2TCOBZHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-03 16:57 UTC, merged